apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-earth-rest-api
  name: hello-earth-rest-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-earth-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-earth-rest-api
    spec:
      containers:
      - image: gcr.io/sb-ito-services-1000153237/hello-earth-rest-api:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent
        name: hello-earth-rest-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-earth-rest-api
  name: hello-earth-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-earth-rest-api
  sessionAffinity: None
  type: LoadBalancer